name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci
  

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge
        run: forge install

      - name: Install yarn
        run: yarn install

      - name: create env file
        run: |
          touch .env
          echo INFURA_API_KEY=$INFURA_API_KEY >> .env
          echo SWAP_ROUTER_ADDRESS=$SWAP_ROUTER_ADDRESS >> .env
        env:
          INFURA_API_KEY: ${{ vars.INFURA_API_KEY }}
          SWAP_ROUTER_ADDRESS: ${{ vars.SWAP_ROUTER_ADDRESS }}
      - name: Run tests
        run: yarn test
